package com.tiktok.sparkling.methods.cimoc.cimoc.webdavputfile

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsWebdavPutFileMethodIDL : AbsSparklingIDLMethod<AbsWebdavPutFileMethodIDL.IDLMethodWebdavPutFileInputModel, AbsWebdavPutFileMethodIDL.IDLMethodWebdavPutFileResultModel>() {
    @IDLMethodName(name = "cimoc.webdavPutFile", params = ["base", "user", "password", "fileName", "content"], results = ["success", "status"])
    final override val name: String = "cimoc.webdavPutFile"

    @IDLMethodParamModel
    interface IDLMethodWebdavPutFileInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "base")
        val base: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "user")
        val user: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "password")
        val password: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "fileName")
        val fileName: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "content")
        val content: String
    }

    @IDLMethodResultModel
    interface IDLMethodWebdavPutFileResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "status")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "status")
        var status: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float
    }
}
