package com.tiktok.sparkling.methods.cimoc.cimoc.setbackstate

import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 * （手写补录：与 codegen 产物同构，避免重跑 codegen 覆盖手写的 index.ts）
 */
abstract class AbsSetBackStateMethodIDL :
    AbsSparklingIDLMethod<
        AbsSetBackStateMethodIDL.IDLMethodSetBackStateInputModel,
        AbsSetBackStateMethodIDL.IDLMethodSetBackStateResultModel,
    >() {
    @IDLMethodName(name = "cimoc.setBackState", params = ["canGoBack"], results = ["success"])
    final override val name: String = "cimoc.setBackState"

    @IDLMethodParamModel
    interface IDLMethodSetBackStateInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "canGoBack")
        val canGoBack: Boolean
    }

    @IDLMethodResultModel
    interface IDLMethodSetBackStateResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean?
    }
}
