package com.tiktok.sparkling.methods.cimoc.cimoc.scanlocalcomics

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsScanLocalComicsMethodIDL : AbsSparklingIDLMethod<AbsScanLocalComicsMethodIDL.IDLMethodScanLocalComicsInputModel, AbsScanLocalComicsMethodIDL.IDLMethodScanLocalComicsResultModel>() {
    @IDLMethodName(name = "cimoc.scanLocalComics", results = ["comicsJson"])
    final override val name: String = "cimoc.scanLocalComics"

    @IDLMethodParamModel
    interface IDLMethodScanLocalComicsInputModel : IDLMethodBaseParamModel {
    }

    @IDLMethodResultModel
    interface IDLMethodScanLocalComicsResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "comicsJson")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "comicsJson")
        var comicsJson: String?
    }
}
