package com.tiktok.sparkling.methods.cimoc.cimoc.isnetworkavailable

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsIsNetworkAvailableMethodIDL : AbsSparklingIDLMethod<AbsIsNetworkAvailableMethodIDL.IDLMethodIsNetworkAvailableInputModel, AbsIsNetworkAvailableMethodIDL.IDLMethodIsNetworkAvailableResultModel>() {
    @IDLMethodName(name = "cimoc.isNetworkAvailable", results = ["available"])
    final override val name: String = "cimoc.isNetworkAvailable"

    @IDLMethodParamModel
    interface IDLMethodIsNetworkAvailableInputModel : IDLMethodBaseParamModel {
    }

    @IDLMethodResultModel
    interface IDLMethodIsNetworkAvailableResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "available")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "available")
        var available: Boolean?
    }
}
