package com.tiktok.sparkling.methods.cimoc.cimoc.rustversion

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsRustVersionMethodIDL : AbsSparklingIDLMethod<AbsRustVersionMethodIDL.IDLMethodRustVersionInputModel, AbsRustVersionMethodIDL.IDLMethodRustVersionResultModel>() {
    @IDLMethodName(name = "cimoc.rustVersion", results = ["version"])
    final override val name: String = "cimoc.rustVersion"

    @IDLMethodParamModel
    interface IDLMethodRustVersionInputModel : IDLMethodBaseParamModel {
    }

    @IDLMethodResultModel
    interface IDLMethodRustVersionResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "version")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "version")
        var version: String?
    }
}
