package com.tiktok.sparkling.methods.cimoc.cimoc.getdownloaddir

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsGetDownloadDirMethodIDL : AbsSparklingIDLMethod<AbsGetDownloadDirMethodIDL.IDLMethodGetDownloadDirInputModel, AbsGetDownloadDirMethodIDL.IDLMethodGetDownloadDirResultModel>() {
    @IDLMethodName(name = "cimoc.getDownloadDir", results = ["dir"])
    final override val name: String = "cimoc.getDownloadDir"

    @IDLMethodParamModel
    interface IDLMethodGetDownloadDirInputModel : IDLMethodBaseParamModel {
    }

    @IDLMethodResultModel
    interface IDLMethodGetDownloadDirResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "dir")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "dir")
        var dir: String?
    }
}
