package com.tiktok.sparkling.methods.cimoc.cimoc.downloadchapter

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsDownloadChapterMethodIDL : AbsSparklingIDLMethod<AbsDownloadChapterMethodIDL.IDLMethodDownloadChapterInputModel, AbsDownloadChapterMethodIDL.IDLMethodDownloadChapterResultModel>() {
    @IDLMethodName(name = "cimoc.downloadChapter", params = ["url", "comicId", "chapterIndex", "pageIndex"], results = ["success"])
    final override val name: String = "cimoc.downloadChapter"

    @IDLMethodParamModel
    interface IDLMethodDownloadChapterInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url")
        val url: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "comicId")
        val comicId: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "chapterIndex")
        val chapterIndex: Number

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "pageIndex")
        val pageIndex: Number
    }

    @IDLMethodResultModel
    interface IDLMethodDownloadChapterResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean?
    }
}
