package com.tiktok.sparkling.methods.cimoc.cimoc.crawl

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsCrawlMethodIDL : AbsSparklingIDLMethod<AbsCrawlMethodIDL.IDLMethodCrawlInputModel, AbsCrawlMethodIDL.IDLMethodCrawlResultModel>() {
    @IDLMethodName(name = "cimoc.crawl", params = ["op", "sourceId", "payload"], results = ["json"])
    final override val name: String = "cimoc.crawl"

    @IDLMethodParamModel
    interface IDLMethodCrawlInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "op")
        val op: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "sourceId")
        val sourceId: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "payload")
        val payload: String
    }

    @IDLMethodResultModel
    interface IDLMethodCrawlResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "json")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "json")
        var json: String?
    }
}
