package com.tiktok.sparkling.methods.cimoc.cimoc.webdavgetfile

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsWebdavGetFileMethodIDL : AbsSparklingIDLMethod<AbsWebdavGetFileMethodIDL.IDLMethodWebdavGetFileInputModel, AbsWebdavGetFileMethodIDL.IDLMethodWebdavGetFileResultModel>() {
    @IDLMethodName(name = "cimoc.webdavGetFile", params = ["base", "user", "password", "fileName"], results = ["ok", "content", "status", "error"])
    final override val name: String = "cimoc.webdavGetFile"

    @IDLMethodParamModel
    interface IDLMethodWebdavGetFileInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "base")
        val base: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "user")
        val user: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "password")
        val password: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "fileName")
        val fileName: String
    }

    @IDLMethodResultModel
    interface IDLMethodWebdavGetFileResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "ok")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "ok")
        var ok: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "content")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "content")
        var content: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "status")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "status")
        var status: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "error")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "error")
        var error: String?
    }
}
