package com.tiktok.sparkling.methods.cimoc.cimoc.getvalue

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsGetValueMethodIDL : AbsSparklingIDLMethod<AbsGetValueMethodIDL.IDLMethodGetValueInputModel, AbsGetValueMethodIDL.IDLMethodGetValueResultModel>() {
    @IDLMethodName(name = "cimoc.getValue", params = ["key"], results = ["value"])
    final override val name: String = "cimoc.getValue"

    @IDLMethodParamModel
    interface IDLMethodGetValueInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "key")
        val key: String
    }

    @IDLMethodResultModel
    interface IDLMethodGetValueResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "value")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "value")
        var value: String?
    }
}
