package com.tiktok.sparkling.methods.cimoc.cimoc.setvalue

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsSetValueMethodIDL : AbsSparklingIDLMethod<AbsSetValueMethodIDL.IDLMethodSetValueInputModel, AbsSetValueMethodIDL.IDLMethodSetValueResultModel>() {
    @IDLMethodName(name = "cimoc.setValue", params = ["key", "value"], results = ["success"])
    final override val name: String = "cimoc.setValue"

    @IDLMethodParamModel
    interface IDLMethodSetValueInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "key")
        val key: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "value")
        val value: String
    }

    @IDLMethodResultModel
    interface IDLMethodSetValueResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean?
    }
}
