package com.tiktok.sparkling.methods.cimoc.cimoc.deletecomicdownload

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsDeleteComicDownloadMethodIDL : AbsSparklingIDLMethod<AbsDeleteComicDownloadMethodIDL.IDLMethodDeleteComicDownloadInputModel, AbsDeleteComicDownloadMethodIDL.IDLMethodDeleteComicDownloadResultModel>() {
    @IDLMethodName(name = "cimoc.deleteComicDownload", params = ["comicId"], results = ["success"])
    final override val name: String = "cimoc.deleteComicDownload"

    @IDLMethodParamModel
    interface IDLMethodDeleteComicDownloadInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "comicId")
        val comicId: String
    }

    @IDLMethodResultModel
    interface IDLMethodDeleteComicDownloadResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean?
    }
}
