package com.tiktok.sparkling.methods.cimoc.cimoc.listlocalchapters

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsListLocalChaptersMethodIDL : AbsSparklingIDLMethod<AbsListLocalChaptersMethodIDL.IDLMethodListLocalChaptersInputModel, AbsListLocalChaptersMethodIDL.IDLMethodListLocalChaptersResultModel>() {
    @IDLMethodName(name = "cimoc.listLocalChapters", params = ["comicId"], results = ["chaptersJson"])
    final override val name: String = "cimoc.listLocalChapters"

    @IDLMethodParamModel
    interface IDLMethodListLocalChaptersInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "comicId")
        val comicId: String
    }

    @IDLMethodResultModel
    interface IDLMethodListLocalChaptersResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "chaptersJson")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "chaptersJson")
        var chaptersJson: String?
    }
}
