package com.tiktok.sparkling.methods.cimoc.cimoc.gettext

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsGetTextMethodIDL : AbsSparklingIDLMethod<AbsGetTextMethodIDL.IDLMethodGetTextInputModel, AbsGetTextMethodIDL.IDLMethodGetTextResultModel>() {
    @IDLMethodName(name = "cimoc.getText", params = ["url", "headers"], results = ["status", "body"])
    final override val name: String = "cimoc.getText"

    @IDLMethodParamModel
    interface IDLMethodGetTextInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url")
        val url: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "headers")
        val headers: String?
    }

    @IDLMethodResultModel
    interface IDLMethodGetTextResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "status")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "status")
        var status: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "body")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "body")
        var body: String?
    }
}
