package com.tiktok.sparkling.methods.cimoc.cimoc.listkeys

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsListKeysMethodIDL : AbsSparklingIDLMethod<AbsListKeysMethodIDL.IDLMethodListKeysInputModel, AbsListKeysMethodIDL.IDLMethodListKeysResultModel>() {
    @IDLMethodName(name = "cimoc.listKeys", results = ["keys"])
    final override val name: String = "cimoc.listKeys"

    @IDLMethodParamModel
    interface IDLMethodListKeysInputModel : IDLMethodBaseParamModel {
    }

    @IDLMethodResultModel
    interface IDLMethodListKeysResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "keys", primitiveClassType = String::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "keys", primitiveClassType = String::class)
        var keys: List<String>?
    }
}
