package com.tiktok.sparkling.methods.cimoc.cimoc.listdownloadedchapters

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsListDownloadedChaptersMethodIDL : AbsSparklingIDLMethod<AbsListDownloadedChaptersMethodIDL.IDLMethodListDownloadedChaptersInputModel, AbsListDownloadedChaptersMethodIDL.IDLMethodListDownloadedChaptersResultModel>() {
    @IDLMethodName(name = "cimoc.listDownloadedChapters", params = ["comicId"], results = ["chaptersJson"])
    final override val name: String = "cimoc.listDownloadedChapters"

    @IDLMethodParamModel
    interface IDLMethodListDownloadedChaptersInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "comicId")
        val comicId: String
    }

    @IDLMethodResultModel
    interface IDLMethodListDownloadedChaptersResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "chaptersJson")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "chaptersJson")
        var chaptersJson: String?
    }
}
