package com.tiktok.sparkling.methods.cimoc.cimoc.getbytes

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
abstract class AbsGetBytesMethodIDL : AbsSparklingIDLMethod<AbsGetBytesMethodIDL.IDLMethodGetBytesInputModel, AbsGetBytesMethodIDL.IDLMethodGetBytesResultModel>() {
    @IDLMethodName(name = "cimoc.getBytes", params = ["url"], results = ["status", "base64"])
    final override val name: String = "cimoc.getBytes"

    @IDLMethodParamModel
    interface IDLMethodGetBytesInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url")
        val url: String
    }

    @IDLMethodResultModel
    interface IDLMethodGetBytesResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "status")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "status")
        var status: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "base64")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "base64")
        var base64: String?
    }
}
